create database TSOCSP;
use TSOCSP;
DROP TABLE IF EXISTS ROUTER_CONNECTIVITY_PORT;
DROP TABLE IF EXISTS PROBE_CONNECTIVITY_PORT;
DROP TABLE IF EXISTS FPGA_DETAILS;
DROP TABLE IF EXISTS PROBE_DETAILS;
DROP TABLE IF EXISTS LB_PORT;
DROP TABLE IF EXISTS LB_DETAILS;
DROP TABLE IF EXISTS ROUTER_DETAILS;
DROP TABLE IF EXISTS CONTACT_PERSON;
DROP TABLE IF EXISTS SITES_DETAILS;

CREATE TABLE SITES_DETAILS (
    SITE_ID VARCHAR(20) PRIMARY KEY,
    SITE_ISP VARCHAR(100),
    SITE_LOCATION TEXT,
    SITE_ADDRESS TEXT,
    SITE_INST_VENDOR TEXT,
    SITE_INST_PHASE INT
);

CREATE TABLE PROBE_DETAILS (
    PROBE_ID VARCHAR(20) PRIMARY KEY,
    SITE_ID VARCHAR(20),
    MAKE TEXT,
    MODEL_NO TEXT,
    SERVICE_TAG TEXT,
    ROW_NO TEXT,
    RACK_NAME TEXT,
    RACK_U_NUMBER VARCHAR(20),
    RAM TEXT,
    STORAGE TEXT,
    ILO_IP_ADDRESS VARCHAR(20),
    SERVER_IP_ADDRESS VARCHAR(20),
    SERVER_GATEWAY_ADDRESS VARCHAR(20),
    FPGA_CARD_INSTALL BOOLEAN,
    CERTAIN_NCCC_CONNECT BOOLEAN,
    FOREIGN KEY (SITE_ID) REFERENCES SITES_DETAILS(SITE_ID)
);

CREATE TABLE FPGA_DETAILS (
    FPGA_ID VARCHAR(20) PRIMARY KEY,
    PROBE_ID VARCHAR(20),
    FPGA_CARD_MAKE TEXT,
    FPGA_MODEL_NO TEXT,
    FPGA_SERIAL_NO VARCHAR(20),
    FPGA_NUMBER_OF_CARDS_IN_PROBE INT,
    FOREIGN KEY (PROBE_ID) REFERENCES PROBE_DETAILS(PROBE_ID)
);

CREATE TABLE ROUTER_DETAILS (
    ROUTE_ID VARCHAR(20) PRIMARY KEY,
    ROUTER_MAKE TEXT,
    ROUTER_MODEL_NO TEXT,
    ROUTER_SERIAL_NO VARCHAR(20),
    ROW_NO TEXT,
    RACK_NAME TEXT,
    RACK_U_NUMBER VARCHAR(20),
    ROUTER_IP VARCHAR(20),
    GATEWAY_IP VARCHAR(20)
);

CREATE TABLE PROBE_CONNECTIVITY_PORT (
    PROBE_CONNECTIVITY_PORT_ID VARCHAR(20) PRIMARY KEY,
    PORT_NO INT,
    PROBE_ID VARCHAR(20),
    FOREIGN KEY (PROBE_ID) REFERENCES PROBE_DETAILS(PROBE_ID)
);

CREATE TABLE ROUTER_CONNECTIVITY_PORT (
    ROUTER_CONNECTIVITY_PORT_ID VARCHAR(20) PRIMARY KEY,
    PROBE_CONNECTIVITY_PORT_ID VARCHAR(20),
    ROUTE_ID VARCHAR(20),
    SITE_ID VARCHAR(20),
    ROUTER_PORT_NO VARCHAR(20),
    FOREIGN KEY (PROBE_CONNECTIVITY_PORT_ID) REFERENCES PROBE_CONNECTIVITY_PORT(PROBE_CONNECTIVITY_PORT_ID),
    FOREIGN KEY (ROUTE_ID) REFERENCES ROUTER_DETAILS(ROUTE_ID),
    FOREIGN KEY (SITE_ID) REFERENCES SITES_DETAILS(SITE_ID)
);

CREATE TABLE LB_DETAILS (
    LB_ID VARCHAR(20) PRIMARY KEY,
    SITE_ID VARCHAR(20),
    LB_IP VARCHAR(20),
    LB_TYPE TEXT,
    FOREIGN KEY (SITE_ID) REFERENCES SITES_DETAILS(SITE_ID)
);

CREATE TABLE LB_PORT (
    LB_ID VARCHAR(20),
    LB_PORT_NO VARCHAR(20),
    LB_CAPACITY TEXT,
    PRIMARY KEY (LB_ID, LB_PORT_NO),
    FOREIGN KEY (LB_ID) REFERENCES LB_DETAILS(LB_ID)
);

CREATE TABLE CONTACT_PERSON (
    CONTACT_ID VARCHAR(20) PRIMARY KEY,
    PROBE_ID VARCHAR(20),
    SITE_ID VARCHAR(20),
    CONTACT_PERSON_NAME TEXT,
    CONTACT_PERSON_NO VARCHAR(20),
    FOREIGN KEY (PROBE_ID) REFERENCES PROBE_DETAILS(PROBE_ID),
    FOREIGN KEY (SITE_ID) REFERENCES SITES_DETAILS(SITE_ID)
);

CREATE TABLE MPLS_LINK (
    LINK_ID VARCHAR(20) PRIMARY KEY,
    PROBE_ID VARCHAR(20),
    MPLS_PROVIDER TEXT,
    ERP_CP_ID INT,
    CE_ID INT,
    PE_ID INT,
    LINK_CAPACITY INT,
    FOREIGN KEY (PROBE_ID) REFERENCES PROBE_DETAILS(PROBE_ID)
);



#there is contact detail if i want to fetch the contact site and probe table

#in lb_details and lb_Port table correct it in right way

#check if there is any correction

#and apply some check constraints on important details





